server:
  http_listen_port: 12345
prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs:
    - name: integrations
      scrape_configs:
        - job_name: integrations/nodejs
          static_configs:
            - targets:
                - localhost:4001
      remote_write:
        - url: https://prometheus-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: "32448"
            password: eyJrIjoiYzE3OGVjMDQ4YmNmNjBiZWFjY2Y5ZTZjMmRjODViMWY0ZWFhNzVkMCIsIm4iOiJ0YWxsZXIyYWlyYm5iLWVhc3lzdGFydC1wcm9tLXB1Ymxpc2hlciIsImlkIjo0NTgwMjV9
integrations:
  prometheus_remote_write:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: "32448"
        password: eyJrIjoiYzE3OGVjMDQ4YmNmNjBiZWFjY2Y5ZTZjMmRjODViMWY0ZWFhNzVkMCIsIm4iOiJ0YWxsZXIyYWlyYm5iLWVhc3lzdGFydC1wcm9tLXB1Ymxpc2hlciIsImlkIjo0NTgwMjV9
